# 查看数据

In [1]:
import os
import pathlib
import numpy as np
import pandas as pd

In [2]:
from pyltp import SentenceSplitter
import jieba 

def split_sentences(sentences):
    sents = SentenceSplitter.split(sentences)
    return [s for s in sents if len(s) > 0]

def cut(sent):
    return ' '.join(jieba.cut(sent))

def cut_string(string):
    sentences = split_sentences(string)
    return [cut(s) for s in sentences]

In [3]:
root = str(pathlib.Path(os.path.abspath('__file__')).parent)
print(root)

/root/share/HCLG/project2


In [4]:
data = pd.read_csv(os.path.join(root, 'dataset/sqlResult_1558435.csv'), encoding='gb18030')
data.head()

id      author                  source  \
0  89617         NaN  快科技@http://www.kkj.cn/   
1  89616         NaN  快科技@http://www.kkj.cn/   
2  89615         NaN  快科技@http://www.kkj.cn/   
3  89614         NaN                     新华社   
4  89613  胡淑丽_MN7479                   深圳大件事   

                                             content  \
0  此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...   
1  骁龙835作为唯一通过Windows 10桌面平台认证的ARM处理器，高通强调，不会因为只考...   
2  此前的一加3T搭载的是3400mAh电池，DashCharge快充规格为5V/4A。\r\n...   
3    这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
4  （原标题：44岁女子跑深圳约会网友被拒，暴雨中裸身奔走……）\r\n@深圳交警微博称：昨日清...   

                                             feature  \
0  {"type":"科技","site":"cnbeta","commentNum":"37"...   
1  {"type":"科技","site":"cnbeta","commentNum":"15"...   
2  {"type":"科技","site":"cnbeta","commentNum":"18"...   
3  {"type":"国际新闻","site":"环球","commentNum":"0","j...   
4  {"type":"新闻","site":"网易热门","commentNum":"978",...   

                           title  \
0           小米MIUI 9首批机型曝光：共计15款   
1     骁龙835在Windows 10上的性能表现有望改善   
2      一加手机5细节曝光：3300mAh、充半小时用1天   
3  葡森林火灾造成至少62人死亡 政府宣布进入紧急状态（组图）   
4       44岁女子约网友被拒暴雨中裸奔 交警为其披衣相随   

                                                 url  
0     http://www.cnbeta.com/articles/tech/623597.htm  
1     http://www.cnbeta.com/articles/tech/623599.htm  
2     http://www.cnbeta.com/articles/tech/623601.htm  
3  http://world.huanqiu.com/hot/2017-06/10866126....  
4  http://news.163.com/17/0618/00/CN617P3Q0001875...

# 训练词向量的数据

In [5]:
# data['content']

In [7]:
data['combined'] = data['content'] + data['title']
data.head(2)

id author                  source  \
0  89617    NaN  快科技@http://www.kkj.cn/   
1  89616    NaN  快科技@http://www.kkj.cn/   

                                             content  \
0  此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...   
1  骁龙835作为唯一通过Windows 10桌面平台认证的ARM处理器，高通强调，不会因为只考...   

                                             feature  \
0  {"type":"科技","site":"cnbeta","commentNum":"37"...   
1  {"type":"科技","site":"cnbeta","commentNum":"15"...   

                        title                                             url  \
0        小米MIUI 9首批机型曝光：共计15款  http://www.cnbeta.com/articles/tech/623597.htm   
1  骁龙835在Windows 10上的性能表现有望改善  http://www.cnbeta.com/articles/tech/623599.htm   

                                            combined  
0  此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...  
1  骁龙835作为唯一通过Windows 10桌面平台认证的ARM处理器，高通强调，不会因为只考...

In [8]:
data['combined'][0].replace('\r', '').replace('\r', '')

'此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/体验版内测，稳定版暂不受影响），以确保工程师可以集中全部精力进行系统优化工作。有人猜测这也是将精力主要用到MIUI 9的研发之中。\nMIUI 8去年5月发布，距今已有一年有余，也是时候更新换代了。\n当然，关于MIUI 9的确切信息，我们还是等待官方消息。\n小米MIUI 9首批机型曝光：共计15款'

In [9]:
data = data.dropna(subset=['content'])

In [10]:
data['combined'][0]

'此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/体验版内测，稳定版暂不受影响），以确保工程师可以集中全部精力进行系统优化工作。有人猜测这也是将精力主要用到MIUI 9的研发之中。\r\nMIUI 8去年5月发布，距今已有一年有余，也是时候更新换代了。\r\n当然，关于MIUI 9的确切信息，我们还是等待官方消息。\r\n小米MIUI 9首批机型曝光：共计15款'

In [11]:
cut(data['combined'][0].replace('\n', '').replace('\r', ''))

Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.965 seconds.
Prefix dict has been built successfully.


'此外 ， 自 本周 （ 6 月 12 日 ） 起 ， 除 小米 手机 6 等 15 款 机型 外 ， 其余 机型 已 暂停 更新 发布 （ 含 开发 版 / 体验版 内测 ， 稳定版 暂不受 影响 ） ， 以 确保 工程师 可以 集中 全部 精力 进行 系统优化 工作 。 有人 猜测 这 也 是 将 精力 主要 用到 MIUI   9 的 研发 之中 。 MIUI   8 去年 5 月 发布 ， 距今已有 一年 有余 ， 也 是 时候 更新换代 了 。 当然 ， 关于 MIUI   9 的 确切 信息 ， 我们 还是 等待 官方消息 。 小米 MIUI   9 首批 机型 曝光 ： 共计 15 款'

In [105]:
# data_list[-1].strip().replace('\u3000', '').replace('\\ n', '')

In [12]:
from tqdm import tqdm

## 保存到文件，并于wiki的数据进行合并

In [13]:
# with open('dataset/content_cut.txt', 'a', encoding='utf-8') as f:
#     for line in tqdm(data['combined']):
#         f.write(cut(line.replace('\n', '').replace('\r', '')))
# #         f.write('\n')

In [14]:
test = data['content'][0]
print(test)

此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/体验版内测，稳定版暂不受影响），以确保工程师可以集中全部精力进行系统优化工作。有人猜测这也是将精力主要用到MIUI 9的研发之中。
MIUI 8去年5月发布，距今已有一年有余，也是时候更新换代了。
当然，关于MIUI 9的确切信息，我们还是等待官方消息。



In [15]:
sents = cut_string(test)
print(sents)

['此外 ， 自 本周 （ 6 月 12 日 ） 起 ， 除 小米 手机 6 等 15 款 机型 外 ， 其余 机型 已 暂停 更新 发布 （ 含 开发 版 / 体验版 内测 ， 稳定版 暂不受 影响 ） ， 以 确保 工程师 可以 集中 全部 精力 进行 系统优化 工作 。', '有人 猜测 这 也 是 将 精力 主要 用到 MIUI   9 的 研发 之中 。', 'MIUI   8 去年 5 月 发布 ， 距今已有 一年 有余 ， 也 是 时候 更新换代 了 。', '当然 ， 关于 MIUI   9 的 确切 信息 ， 我们 还是 等待 官方消息 。']


In [16]:
import SIF.src.data_io as data_io
import SIF.src.params as params
import SIF.src.SIF_embedding as SIF_embedding

In [17]:
wordfile = '/root/share/model/zhwiki_embedding_256.bin'
weightfile = os.path.join('/root/share/HCLG/project2/SIF/auxiliary_data/cnwiki_vocab.txt') # each line is a word and its frequency
weightpara = 1e-3 # the parameter in the SIF weighting scheme, usually in the range [3e-5, 3e-3]
rmpc = 1 # number of principal components to remove in SIF weighting scheme(是否去掉最大主成分项)

In [18]:
(words, We) = data_io.getWordmap(wordfile)

In [19]:
# with open(weightfile, 'r', encoding='utf-8') as f:
#     weight = f.readlines()

In [20]:
# load word weights
word2weight = data_io.getWordWeight(weightfile, weightpara) # word2weight['str'] is the weight for the word 'str'
weight4ind = data_io.getWeight(words, word2weight) # weight4ind[i] is the weight for the i-th word

In [21]:
# load sentences
x, m = data_io.sentences2idx(sents, words)

In [22]:
w = data_io.seq2weight(x, m, weight4ind) # get word weights

In [23]:
# set parameters
params = params.params()
params.rmpc = rmpc
# get SIF embedding
embedding = SIF_embedding.SIF_embedding(We, x, w, params) # embedding[i,:] is the embedding for sentence i

##  每个句子的句向量: <V0, V1, V2, ..., Vn>

In [24]:
embedding

array([[-0.31514071, -0.56987926, -0.01390499, ...,  0.13497118,
         1.12674616, -0.43519123],
       [ 0.01419883,  0.12753887,  0.18750542, ...,  0.04438578,
        -0.58553998, -0.09420235],
       [ 0.23185268, -0.3511752 , -0.07844421, ...,  0.25428663,
         0.54273232, -0.09030766],
       [-0.05585932,  0.43387274, -0.09716297, ..., -0.30828524,
        -0.43729487,  0.35779271]])

In [25]:
test_title = data['title'][0].replace(' ', '')
test_title

'小米MIUI9首批机型曝光：共计15款'

In [26]:
titles = cut_string(test_title)
titles

['小米 MIUI9 首批 机型 曝光 ： 共计 15 款']

In [27]:
title_x, title_m = data_io.sentences2idx(titles, words)
title_w = data_io.seq2weight(title_x, title_m, weight4ind)
title_embedding = SIF_embedding.SIF_embedding(We, title_x, title_w, params)

/root/share/py37/lib/python3.7/site-packages/sklearn/decomposition/_truncated_svd.py:197: RuntimeWarning: invalid value encountered in true_divide
  self.explained_variance_ratio_ = exp_var / full_var


In [28]:
title_embedding

array([[ 1.11022302e-16, -1.38777878e-17,  0.00000000e+00,
         2.77555756e-17,  1.38777878e-17, -1.11022302e-16,
         2.22044605e-16,  2.77555756e-17,  5.55111512e-17,
        -1.11022302e-16, -5.55111512e-17,  1.11022302e-16,
        -1.11022302e-16, -2.77555756e-17, -2.77555756e-17,
         2.22044605e-16,  2.22044605e-16, -2.77555756e-17,
        -4.44089210e-16,  6.93889390e-18, -4.44089210e-16,
         2.77555756e-17, -2.22044605e-16,  6.93889390e-18,
         5.55111512e-17,  1.11022302e-16,  5.55111512e-17,
         5.55111512e-17, -5.55111512e-17,  5.55111512e-17,
        -1.11022302e-16,  0.00000000e+00,  2.77555756e-17,
         1.38777878e-17, -2.22044605e-16,  5.55111512e-17,
         5.55111512e-17,  5.55111512e-17,  1.11022302e-16,
         1.11022302e-16,  6.93889390e-18, -5.55111512e-17,
        -5.55111512e-17, -2.22044605e-16,  1.11022302e-16,
         1.11022302e-16, -6.93889390e-18, -2.77555756e-17,
        -5.55111512e-17,  1.38777878e-17,  2.77555756e-1

In [29]:
import numpy as np

In [30]:
def euclidean_distance(x1, x2):
    return np.sqrt(np.power(x1-x2,2).sum())

In [31]:
euclidean_distance(title_embedding[0], embedding[0])

4.327866910154118

In [32]:
euclidean_distance(title_embedding[0], embedding[1])

4.3067576851583205

In [33]:
euclidean_distance(title_embedding[0], embedding[2])

4.37685473018191

In [34]:
euclidean_distance(title_embedding[0], embedding[3])

3.2951434324141733

In [35]:
# !pip3 install scikit-fda -i https://mirrors.aliyun.com/pypi/simple/

In [36]:
test_score = [4.277586200598373, 4.226074333307235, 4.337807828896572, 3.2313757743646665]
test_y = [1, 1, 0, 1]

In [37]:
import pandas as pd

In [38]:
# from sklearn.neighbors import KNeighborsClassifier
# knn = KNeighborsClassifier(n_neighbors=1)
# knn.fit(test_score.reshape(-1, 1), test_y)

In [39]:
# knn.predict(test_score.reshape(-1, 1))

In [40]:
import skfda
import skfda.preprocessing.smoothing.kernel_smoothers as ks
import skfda.preprocessing.smoothing.validation as val

In [41]:
knn = ks.KNeighborsSmoother(smoothing_parameter=2)

In [42]:
[[i for i in range(1, len(test_score)+1)]]

[[1, 2, 3, 4]]

In [43]:
from skfda import FDataGrid
fd = FDataGrid(
    sample_points=test_score,
    data_matrix=[[1, 2, 3, 4]])

In [44]:
fd_smoothed = knn.fit_transform(fd)

In [45]:
fd_smoothed.data_matrix.round(2)

array([[[1.5],
        [1.5],
        [2. ],
        [3. ]]])

In [46]:
[i[0] for i in fd_smoothed.data_matrix.round(2)[0]]

[1.5, 1.5, 2.0, 3.0]

In [47]:
4//3

1